### ISSUE TITLE
Could not find a JavaScript runtime.

### ISSUE THREAD

**Issue by davecramer** [daamien/pgDashboard#1]
after 
dashing start 
received the above error message

**Comment by daamien** [comment]
This means that you need to install a javascript runtime. nodejs would be the best choice. 

Depending on your operating system, this can be tricky...

If you're on the latest ubuntu, the following command should work : `sudo apt-get install nodejs`

On other system, I would recommend reading the following page: 
https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager

**Comment by davecramer** [comment]
Ya I figured that out. Perhaps add to requirements ?

**Comment by daamien** [comment]
done ! 

https://github.com/daamien/PostgreSQL-Dashboard/commit/be5d44d195a068f7ad997d7bdbf96fbec938d5b4#diff-7d442b7eb49f5fc377f51e74b291cfc1

Thanks for the report !
