### ISSUE TITLE
Not updating dashboards

### ISSUE THREAD

**Issue by davecramer** [daamien/pgDashboard#2]
This did work for a while, but not the dashboards aren't updating.

How do I debug this ?

**Comment by daamien** [comment]
Hi ! 
- Does it happen on all widgets or just one ? 
- Is there data in the history.yml ?
- Do have an error when you launch `dashing start` ?

**Comment by davecramer** [comment]
Happens on all widgets,

There are no errors

there is data in history.yml

Interestingly I get data if I restart it?

Dave Cramer

**Comment by daamien** [comment]
hi thanks for the quick reply,

A few more questions:
- What is your current browser ? Do you extensions installed such as adblock or anything else ?
- Can you edit the `assets/javascripts/application.coffee`, add `Dashing.debugMode = true`, relaunch dashing, then open your browser debug console and check if there's errors ?
- Did you try with another browser ? If not can you try with a dead simple browser like [midori](http://www.midori-browser.org/) ?

**Comment by davecramer** [comment]
Hi Damien,

This is likely an issue with my network. debug mode will help.

Have you ever put this behind nginx acting as a proxy?

Dave

Dave Cramer

**Comment by davecramer** [comment]
Looks like /events is not returning ???

Dave Cramer

**Comment by daamien** [comment]
Hi Dave, 

Sorry I have no particular experience with nginx, but it's a standard Sinatra app so the doc below may be usefull for you: 

http://recipes.sinatrarb.com/p/deployment/nginx_proxied_to_unicorn

About the problem with /events, do you see errors in the console log ?

**Comment by davecramer** [comment]
Hi Damien,

No no errors. It seems like the /events just doesn't return ??

This is on pg 8.4 but I rewrote the queries to work properly.

Dave Cramer

**Comment by daamien** [comment]
ok.

You can send me the queries you rewrote for 8.4 and I'll had them to the project if you want. 

Anyway PostgreSQL 8.4 is now obsolete, you should upgrade :)

**Comment by daamien** [comment]
patch merged

**Comment by Mwajeeh54** [comment]
i have an error when i launch dashing start
